import type { PrimerTokens } from '../types';

// Spacing, typography, radii, and borders are mode-independent and match light defaults.
export const defaultDarkTokens: PrimerTokens = {
  colors: {
    primary: '#2f98ff',
    background: '#171619',
    surface: '#292929',
    overlay: 'rgba(0,0,0,0.7)',
    textPrimary: '#efefef',
    textSecondary: '#c7c7c7',
    textPlaceholder: '#767577',
    textDisabled: '#858585',
    textNegative: '#f6bfbf',
    textLink: '#4aaeff',
    border: '#424242',
    borderFocused: '#2f98ff',
    borderError: '#e46d70',
    borderDisabled: '#292929',
    iconPrimary: '#efefef',
    iconDisabled: '#858585',
    iconNegative: '#e46d70',
    iconPositive: '#27b17d',
    error: '#e46d70',
    success: '#27b17d',
  },
  spacing: {
    xxsmall: 2,
    xsmall: 4,
    small: 8,
    medium: 12,
    large: 16,
    xlarge: 20,
    xxlarge: 24,
    xxxlarge: 32,
  },
  typography: {
    fontFamily: 'Inter',
    titleXLarge: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
      letterSpacing: -0.6,
      fontFamily: 'Inter',
    },
    titleLarge: {
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 20,
      letterSpacing: -0.2,
      fontFamily: 'Inter',
    },
    bodyLarge: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: -0.2,
      fontFamily: 'Inter',
    },
    bodyMedium: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: 0,
      fontFamily: 'Inter',
    },
    bodySmall: {
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
      letterSpacing: 0,
      fontFamily: 'Inter',
    },
  },
  radii: {
    none: 0,
    xsmall: 2,
    small: 4,
    medium: 8,
    large: 12,
  },
  borders: {
    default: 1,
    input: 1,
    strong: 2,
  },
};
