import type { PrimerTokens } from '../types';

// Values derived from iOS dark.json (Style Dictionary generated, dark theme).
// Source: primer-sdk-ios: Modules/PrimerResources/.../JSONs/dark.json
// Spacing, typography, radii, and widths are mode-independent and match light defaults.
export const defaultDarkTokens: PrimerTokens = {
  colors: {
    backgroundOutlinedActive: '#171619',
    backgroundOutlinedDefault: '#171619',
    backgroundOutlinedDisabled: '#efefef0a',
    backgroundOutlinedError: '#171619',
    backgroundOutlinedHover: '#171619',
    backgroundOutlinedLoading: '#efefef0a',
    backgroundOutlinedSelected: '#171619',
    backgroundPrimary: '#171619',
    backgroundSecondary: '#efefef0a',
    backgroundTransparentActive: '#efefef12',
    backgroundTransparentDefault: '#ffffff00',
    backgroundTransparentDisabled: '#efefef0a',
    backgroundTransparentHover: '#efefef0a',
    backgroundTransparentLoading: '#efefef0a',
    backgroundTransparentSelected: '#efefef0a',
    blue500: '#3f93e4',
    blue900: '#4aaeff',
    borderOutlinedActive: '#efefef70',
    borderOutlinedDefault: '#efefef24',
    borderOutlinedDisabled: '#efefef12',
    borderOutlinedError: '#e46d70',
    borderOutlinedFocus: '#2f98ff',
    borderOutlinedHover: '#efefef4d',
    borderOutlinedLoading: '#efefef12',
    borderOutlinedSelected: '#2f98ff',
    borderTransparentActive: '#ffffff00',
    borderTransparentDefault: '#ffffff00',
    borderTransparentDisabled: '#ffffff00',
    borderTransparentFocus: '#2f98ff',
    borderTransparentHover: '#ffffff00',
    borderTransparentSelected: '#ffffff00',
    brand: '#2f98ff',
    focus: '#2f98ff',
    gray000: '#171619',
    gray100: '#efefef0a',
    gray200: '#efefef12',
    gray300: '#efefef24',
    gray400: '#efefef4d',
    gray500: '#efefef70',
    gray600: '#efefef9e',
    gray900: '#efefef',
    green500: '#27b17d',
    iconDisabled: '#efefef4d',
    iconNegative: '#e46d70',
    iconPositive: '#27b17d',
    iconPrimary: '#efefef',
    loader: '#2f98ff',
    onBrand: '#ffffff',
    overlay: 'rgba(0,0,0,0.5)',
    red100: '#321c20',
    red500: '#e46d70',
    red900: '#f6bfbf',
    textDisabled: '#efefef4d',
    textLink: '#4aaeff',
    textNegative: '#f6bfbf',
    textOutlinedDefault: '#efefef',
    textPlaceholder: '#efefef70',
    textPrimary: '#efefef',
    textSecondary: '#efefef9e',
  },
  spacing: {
    xxsmall: 2,
    xsmall: 4,
    small: 8,
    medium: 12,
    large: 16,
    xlarge: 20,
    xxlarge: 24,
    xxxlarge: 32,
  },
  typography: {
    fontFamily: 'Inter',
    titleXLarge: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
      letterSpacing: -0.6,
      fontFamily: 'Inter',
    },
    titleLarge: {
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 20,
      letterSpacing: -0.2,
      fontFamily: 'Inter',
    },
    bodyLarge: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: -0.2,
      fontFamily: 'Inter',
    },
    bodyMedium: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: 0,
      fontFamily: 'Inter',
    },
    bodySmall: {
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
      letterSpacing: 0,
      fontFamily: 'Inter',
    },
    error: {
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
      letterSpacing: 0,
      fontFamily: 'Inter',
    },
  },
  radii: {
    none: 0,
    xsmall: 2,
    small: 4,
    medium: 8,
    large: 12,
  },
  sizes: {
    small: 16, // primerSizeSmall
    medium: 20, // primerSizeMedium
    large: 24, // primerSizeLarge
    xlarge: 32, // primerSizeXlarge
    xxlarge: 40, // primerSizeXxlarge
    xxxlarge: 56, // primerSizeXxxlarge
    base: 4, // primerSizeBase
  },
  widths: {
    default: 1,
    focus: 2,
    selected: 2,
    error: 2,
  },
};
