import type { PrimerTokens } from '../types';

export const defaultLightTokens: PrimerTokens = {
  colors: {
    primary: '#2f98ff',
    background: '#ffffff',
    surface: '#f5f5f5',
    overlay: 'rgba(0,0,0,0.5)',
    textPrimary: '#212121',
    textSecondary: '#757575',
    textPlaceholder: '#9e9e9e',
    textDisabled: '#bdbdbd',
    textNegative: '#b4324b',
    textLink: '#2270f4',
    border: '#e0e0e0',
    borderFocused: '#2f98ff',
    borderError: '#ff7279',
    borderDisabled: '#eeeeee',
    iconPrimary: '#212121',
    iconDisabled: '#bdbdbd',
    iconNegative: '#ff7279',
    iconPositive: '#3eb68f',
    error: '#ff7279',
    success: '#3eb68f',
  },
  spacing: {
    xxsmall: 2,
    xsmall: 4,
    small: 8,
    medium: 12,
    large: 16,
    xlarge: 20,
    xxlarge: 24,
    xxxlarge: 32,
  },
  typography: {
    fontFamily: 'Inter',
    titleXLarge: {
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
      letterSpacing: -0.6,
      fontFamily: 'Inter',
    },
    titleLarge: {
      fontSize: 16,
      fontWeight: '600',
      lineHeight: 20,
      letterSpacing: -0.2,
      fontFamily: 'Inter',
    },
    bodyLarge: {
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: -0.2,
      fontFamily: 'Inter',
    },
    bodyMedium: {
      fontSize: 14,
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: 0,
      fontFamily: 'Inter',
    },
    bodySmall: {
      fontSize: 12,
      fontWeight: '400',
      lineHeight: 16,
      letterSpacing: 0,
      fontFamily: 'Inter',
    },
  },
  radii: {
    none: 0,
    xsmall: 2,
    small: 4,
    medium: 8,
    large: 12,
  },
  borders: {
    default: 1,
    input: 1,
    strong: 2,
  },
};
