export enum PrimerInputElementType {
    CARD_NUMBER = "CARD_NUMBER",
    EXPIRY_DATE = "EXPIRY_DATE",
    CVV = "CVV",
    CARDHOLDER_NAME = "CARDHOLDER_NAME",
    OTP = "OTP",
    POSTAL_CODE = "POSTAL_CODE",
    PHONE_NUMBER = "PHONE_NUMBER",
    RETAILER = "RETAILER",
    UNKNOWN = "UNKNOWN"
}
