import type { TranslationMap } from '../types';

const stringRegistry: Record<string, () => TranslationMap> = {
  'ar': () => require('./ar.json'),
  'az': () => require('./az.json'),
  'bg': () => require('./bg.json'),
  'bs': () => require('./bs.json'),
  'ca': () => require('./ca.json'),
  'cs': () => require('./cs.json'),
  'da': () => require('./da.json'),
  'de': () => require('./de.json'),
  'el': () => require('./el.json'),
  'en': () => require('./en.json'),
  'es-AR': () => require('./es-AR.json'),
  'es-MX': () => require('./es-MX.json'),
  'es': () => require('./es.json'),
  'et': () => require('./et.json'),
  'fa': () => require('./fa.json'),
  'fi': () => require('./fi.json'),
  'fil': () => require('./fil.json'),
  'fr': () => require('./fr.json'),
  'he': () => require('./he.json'),
  'hi': () => require('./hi.json'),
  'hr': () => require('./hr.json'),
  'hu': () => require('./hu.json'),
  'hy': () => require('./hy.json'),
  'id': () => require('./id.json'),
  'it': () => require('./it.json'),
  'ja': () => require('./ja.json'),
  'ka': () => require('./ka.json'),
  'kk': () => require('./kk.json'),
  'ko': () => require('./ko.json'),
  'ku': () => require('./ku.json'),
  'ky': () => require('./ky.json'),
  'lt': () => require('./lt.json'),
  'lv': () => require('./lv.json'),
  'mk': () => require('./mk.json'),
  'ms': () => require('./ms.json'),
  'nb': () => require('./nb.json'),
  'nl-BE': () => require('./nl-BE.json'),
  'nl': () => require('./nl.json'),
  'pl': () => require('./pl.json'),
  'pt-BR': () => require('./pt-BR.json'),
  'pt': () => require('./pt.json'),
  'ro': () => require('./ro.json'),
  'ru': () => require('./ru.json'),
  'sk': () => require('./sk.json'),
  'sl': () => require('./sl.json'),
  'sq': () => require('./sq.json'),
  'sr': () => require('./sr.json'),
  'sv': () => require('./sv.json'),
  'th': () => require('./th.json'),
  'tr': () => require('./tr.json'),
  'uk': () => require('./uk.json'),
  'ur-PK': () => require('./ur-PK.json'),
  'uz': () => require('./uz.json'),
  'vi': () => require('./vi.json'),
  'zh-CN': () => require('./zh-CN.json'),
  'zh-HK': () => require('./zh-HK.json'),
  'zh-TW': () => require('./zh-TW.json'),
};

export function getTranslationMap(locale: string): TranslationMap | undefined {
  return stringRegistry[locale]?.();
}

export function hasLocale(locale: string): boolean {
  return locale in stringRegistry;
}
