# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'git@github.com:primer-io/primer-sdk-podspecs.git'

target 'ReactNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactNative
  pod 'PrimerSDK', '~> 0.1.2+1'
end

