import "AndroidFastFile"
import "IOSFastFile"

platform :ios do

end

platform :android do

  desc 'Upload the React Native Android build to Appetize'
  lane :upload_build_to_appetize do
    preview
  end

end
