package com.primerioreactnative.datamodels.extensions.ach

import com.primerioreactnative.datamodels.NamedComponentValidatableData
import com.primerioreactnative.datamodels.ach.StripeAchUserDetailsStepRN
import io.primer.android.components.presentation.paymentMethods.nativeUi.stripe.ach.composable.StripeAchUserDetailsCollectableData
import kotlinx.serialization.Serializable
import com.primerioreactnative.datamodels.ach.StripeAchUserDetailsCollectableDataRN

internal fun StripeAchUserDetailsCollectableData.FirstName.toFirstNameRN() = StripeAchUserDetailsCollectableDataRN.FirstNameRN(value)
internal fun StripeAchUserDetailsCollectableData.LastName.toLastNameRN() = StripeAchUserDetailsCollectableDataRN.LastNameRN(value)
internal fun StripeAchUserDetailsCollectableData.EmailAddress.toEmailAddressRN() = StripeAchUserDetailsCollectableDataRN.EmailAddressRN(value)
