name: Android Appetize

on: pull_request

jobs:
  android-istribute-to-appetize:
    runs-on: ubuntu-latest
    name: "Build and upload app to Appetize 🚀"
    steps:

      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install npm
        run: |
          npm config set legacy-peer-deps true install

      - name: Install packages
        run: |
          yarn

      - name: Distribute the React Native Android app on Appetize 🚀
        run: bundle exec fastlane android preview
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
