name: Danger (JS)

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency: 
  group: ${{ github.ref }}-danger-js
  cancel-in-progress: true

jobs:
  danger-js:
    runs-on: ubuntu-latest
    name: "Run Danger JS"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn install

      - name: Run Danger JS
        run: npx danger ci --dangerfile dangerfile.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}