---
name: iOS BS
on: pull_request
jobs:

  build-and-upload-to-browserstack:
    runs-on: macos-latest
    timeout-minutes: 30
    name: Upload app to Browserstack
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa_github_actions
          known_hosts: unnecessary
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Get npm cache directory
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm config set legacy-peer-deps true install

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Tuist.io
        run: |
          if [ ! -d ".tuist-bin" ]
          then
            curl -Ls https://install.tuist.io | bash
          fi
      - name: Create main.jsbundle
        run: |
          npm run build:ios:release
      - name: Create the Xcode project and workspace
        run: sh ./example/ios/ReactNativeExample/tuist-generate.sh is_ci
      - name: Build and upload to Browserstack 🚀
        run: |
          bundle exec fastlane ios qa_release
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Save Browserstack ID
        uses: actions/upload-artifact@v3
        id: save_browserstack_id_step
        with:
          name: browserstack_id
          path: /var/tmp/browserstack_id.txt
          if-no-files-found: error
  test-via-browserstack:
    runs-on: ubuntu-latest
    needs: build-and-upload-to-browserstack
    name: Browserstack test
    steps:
      - name: Install Appium SSH repo key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_MOBILE_APPIUM }}
          name: id_rsa_github_actions_appium
          known_hosts: unnecessary
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_MOBILE_APPIUM }}
      - name: Clone and launch Browserstack tests via Appium 🧪
        run: >
          git clone -b develop git@github.com:primer-io/primer-mobile-appium.git .

      - name: Retrieve Browserstack ID
        uses: actions/download-artifact@v3
        with:
          name: browserstack_id
          path: /var/tmp
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18.3.0

      - name: npm Install
        run: npm install

      - name: Run Appium Test
        env:
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
        run: |
          export BROWSERSTACK_APP_ID=$(cat /var/tmp/browserstack_id.txt)
          echo $BROWSERSTACK_APP_ID
          npx wdio config/wdio.rn.ios.bs.conf.js
