---
name: iOS Appetize
on: pull_request
jobs:
  build-and-upload-to-appetize:
    runs-on: macos-latest
    timeout-minutes: 30
    name: Build and upload app to Appetize 🚀
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa_github_actions
          known_hosts: unnecessary
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Get npm cache directory
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm config set legacy-peer-deps true install

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn
      - name: Install Tuist.io
        run: |
          if [ ! -d ".tuist-bin" ]
          then
            curl -Ls https://install.tuist.io | bash
          fi
      - name: Create the Xcode project and workspace
        run: sh ./example/ios/ReactNativeExample/tuist-generate.sh is_ci

      - name: Create main.jsbundle
        run: |
          npm run build:ios:dev
      - name: Distribute the React Native iOS app on Appetize 🚀
        run: |
          bundle exec fastlane ios appetize_build_and_upload
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Save Simulator app
        uses: actions/upload-artifact@v3
        id: save_simulator_app_id_step
        with:
          name: PrimerSDK_Debug_Build
          path: /var/tmp/PrimerSDK_Debug_Build.zip
          if-no-files-found: error
