name: Preview

on: pull_request

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true

      - name: Preview app on Appetize 🚀
        run: bundle exec fastlane preview
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SOURCE_BRANCH: ${{ github.head_ref }}
          APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
