name: Run Jest Tests

on: pull_request

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Execute Jest Unit Tests

    steps:
      - name: Cancel previous run workflows
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run Jest Tests
        run: yarn test
        env:
          CI: true

      - name: Post test results to GitHub PR
        if: always()  # This ensures the report step runs whether the tests pass or fail
        run: |
          echo "Test results summary" >> ${{ github.workspace }}/test-results.md
          gh pr comment ${{ github.event.pull_request.number }} --body-file ${{ github.workspace }}/test-results.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
