---
name: Validate SDK
on: pull_request
jobs:

  validate:
    runs-on: ubuntu-latest
    name: Validate SDK
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # v0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Git Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Create Keys.ts
        shell: bash
        run: |
          echo "export const STRIPE_ACH_PUBLISHABLE_KEY = '${{ secrets.STRIPE_PUBLISHABLE_KEY }}'" > example/src/Keys.ts

      - name: Cache Yarn dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/install-state.gz
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: |
          yarn

      - name: Build SDK
        run: yarn build

      - name: Verify build artifacts
        run: |
          # Check that essential build artifacts exist
          if [ ! -f "lib/module/index.js" ]; then
            echo "❌ Module build artifact missing"
            exit 1
          fi
          
          if [ ! -f "lib/typescript/src/index.d.ts" ]; then
            echo "❌ TypeScript definitions missing"
            exit 1
          fi
          
          echo "✅ All build artifacts present"

      - name: Check package can be packed
        run: |
          npm pack --dry-run
          echo "✅ Package can be packed successfully"
